name: Your New Jekyll Site
pygments: true
source: ./docs
permalink: none
markdown: kramdown
kramdown:
  use_coderay: true
assets:
  sources:
    - ../lib/assets/fonts
    - ../lib/assets/stylesheets
    - ../lib/assets/javascripts
  compress:
    css:  sass
