name: Your New Jekyll Site
pygments: true
source: ./docs
permalink: none
assets:
  sources:
    - ../lib/assets/fonts
    - ../lib/assets/stylesheets
    - ../lib/assets/javascripts
  compress:
    css:  sass
